version: '3.5'

services:
  db:
    image: postgres:12-bullseye
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    container_name: postgres
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
